version: '3'
services:
  client:
    build:
      context: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/m3ntors
  courses:
    build:
      context: ./courses
      dockerfile: Dockerfile.dev
    env_file:
      - courses/.env
    ports:
      - "8001:8000"
    volumes:
      - ./courses:/src/courses
  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      # Add other backend db directories here and postgres will automatically
      # run `npm run dev` on them (this command should set the database up for
      # that service)
      # Make sure to volume the services as:
      # - ./{backend}/db:/postgres/migrations/{backend}
      - ./courses/db:/home/postgres/migrations/courses
